---
title: "Determinants of HIV"

number_sections: yes
highlight: zenburn
date: December 4th, 2014
output:
  beamer_presentation:
    theme: "CambridgeUS"
    fonttheme: "structurebold"

---

## Outline

- Motivation
- Research Question
- Methodology and Datasets
- Findings
- Conclusion and Limitations

## Motivation

## Research Question

This paper aims to provide evidence to assess why some countries struggle to achieve MDG 6A. We believe that one possible explanation for the failure of some interventions in reducing HIV/AIDS may lie in the lack of a full understanding of the determinants of the disease, which can in turn lead to ill-specified interventions and wrongly targeted campaigns.

The literature reviewed for this paper identifies a myriad of determinants of health. However, there is a gap in the literature when it comes to the determinants of specific diseases. The aim of this paper is to test the applicability of one of the most commonly used theories of determinants of health, to explain the evolution of HIV/AIDS rates. The first hypothesis of this paper is that all general determinants of health (as identified by our reference model) are determinants of HIV/AIDS. By identifying variables that help to explain HIV/AIDS incidence and prevalence, this paper will help move forward the discussion of the determinants of HIV/AIDS . 

Furthermore, given that the literature identifies interlinkages between the different determinants of health (see @Solar2010), this paper will evaluate to what extent those linkages are reflected on the micro level. The second hypothesis of this paper is that socioeconomic, environmental and cultural factors can be used to explain individual lifestyle factors.

## Methodology and Dataset

## Findings

```{r, echo=FALSE}
plot(cars)
```

## Conclusions and Limitation
